--
-- Plik wygenerowany przez SQLiteStudio v3.4.3 dnia sob. sty 13 22:38:42 2024
--
-- Użyte kodowanie tekstu: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Tabela: Pola
CREATE TABLE IF NOT EXISTS Pola (pozycja INTEGER PRIMARY KEY, nazwa_pola TEXT, koszt_kupna_pola INTEGER, koszt_1_domu INTEGER, koszt_2_domow INTEGER, koszt_3_domow INTEGER, koszt_hotelu INTEGER, czynsz_pole REAL, czynsz_1_dom REAL, czynsz_2_dom REAL, czynsz_3_dom REAL, czynsz_hotel REAL, czynsz_1_plaża REAL, czynsz_2_plaże REAL, czynsz_3_plaże REAL, czynsz_4_plaże REAL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (0, 'START', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (1, 'GRENADA', 60, 50, 50, 50, 150, 3.0, '27,5', 48.0, '73,5', 144.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (2, 'SEWILLA', 60, 50, 50, 50, 150, 3.0, '27,5', 48.0, '73,5', 144.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (3, 'MADRYT', 60, 50, 50, 50, 150, 3.0, '27,5', 64.0, '94,5', 180.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (4, 'BALI', 200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25.0, 50.0, 100.0, 200.0);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (5, 'HONGKONG', 100, 50, 50, 50, 150, 5.0, 30.0, 60.0, 100.0, 200.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (6, 'PEKIN', 100, 50, 50, 50, 150, 5.0, '37,5', 80.0, 100.0, 200.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (7, 'SZANGHAJ', 120, 50, 50, 50, 150, 6.0, 34.0, 77.0, 108.0, 231.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (8, 'BEZLUDNA WYSPA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (9, 'WENECJA', 140, 100, 100, 100, 250, 7.0, 72.0, 136.0, 220.0, '379,5', NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (10, 'MEDIOLAN', 140, 100, 100, 100, 250, 7.0, 72.0, 153.0, 220.0, 414.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (11, 'RZYM', 160, 100, 100, 100, 250, 16.0, 78.0, 162.0, 230.0, 426.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (12, 'SZANSA ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (13, 'HAMBURG', 180, 100, 100, 100, 250, 18.0, 84.0, 171.0, 264.0, '474,5', NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (14, 'CYPR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25.0, 50.0, 100.0, 200.0);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (15, 'BERLIN', 200, 100, 100, 100, 250, 20.0, 90.0, 180.0, 275.0, '487,5', NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (16, 'MISTRZOSTWA ŚWIATA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (17, 'LONDYN', 220, 150, 150, 150, 380, 22.0, 111.0, 234.0, 335.0, 630.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (18, 'DUBAJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25.0, 50.0, 100.0, 200.0);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (19, 'SYDNEY', 240, 150, 150, 150, 380, 24.0, 117.0, 243.0, 345.0, 642.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (20, 'SZANSA ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (21, 'CHICAGO', 260, 150, 150, 150, 380, 26.0, 123.0, 252.0, '390,5', '708,5', NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (22, 'LAS VEGAS', 260, 150, 150, 150, 380, 26.0, '143,5', 280.0, '390,5', 763.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (23, 'NOWY JORK', 280, 150, 150, 150, 380, 28.0, '150,5', 290.0, 438.0, 777.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (24, 'PODRÓŻ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (25, 'NICEA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25.0, 50.0, 100.0, 200.0);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (26, 'LYON', 300, 200, 200, 200, 500, 30.0, 175.0, 350.0, 495.0, 910.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (27, 'PARYŻ', 320, 200, 200, 200, 500, 32.0, 182.0, 360.0, 552.0, 994.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (28, 'SZANSA ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (29, 'KRAKÓW', 350, 200, 200, 200, 500, 35.0, 192.5, 375.0, 570.0, 1015.0, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (30, 'PODATEK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO Pola (pozycja, nazwa_pola, koszt_kupna_pola, koszt_1_domu, koszt_2_domow, koszt_3_domow, koszt_hotelu, czynsz_pole, czynsz_1_dom, czynsz_2_dom, czynsz_3_dom, czynsz_hotel, czynsz_1_plaża, czynsz_2_plaże, czynsz_3_plaże, czynsz_4_plaże) VALUES (31, 'WARSZAWA', 400, 200, 200, 200, 500, 40.0, 210.0, 400.0, 600.0, 1125.0, NULL, NULL, NULL, NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
